apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: test-project
  sources:
    - repoURL: https://github.com/chmikata/argo-sub1.git
      path: manifests/nginx
      targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
